In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [ ]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

--2025-11-02 19:46:57--  https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 874188 (854K) [text/plain]
Saving to: ‘car_fuel_efficiency.csv.1’

car_fuel_efficiency 100%[===================>] 853.70K  --.-KB/s    in 0.09s

2025-11-02 19:46:57 (9.23 MB/s) - ‘car_fuel_efficiency.csv.1’ saved [874188/874188]

In [4]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

In [6]:
## fill missing values
df = df.fillna(0)

In [8]:
df.isnull().sum()

engine_displacement    0
num_cylinders          0
horsepower             0
vehicle_weight         0
acceleration           0
model_year             0
origin                 0
fuel_type              0
drivetrain             0
num_doors              0
fuel_efficiency_mpg    0
dtype: int64

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import roc_auc_score

In [12]:
df_full_train , df_test = train_test_split(df, test_size = 0.2, random_state = 1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state =1)

In [13]:
df_train = df_train.reset_index(drop =True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [16]:
df_test

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,4.0,170.0,2770.744260,16.9,2004,Europe,Diesel,Front-wheel drive,0.0,15.865949
1,230,5.0,135.0,2546.670530,11.5,2001,Europe,Gasoline,Front-wheel drive,1.0,17.885965
2,160,4.0,179.0,3845.204498,14.9,2021,Asia,Diesel,All-wheel drive,1.0,10.882701
3,230,5.0,0.0,3006.216277,14.7,2017,Europe,Diesel,All-wheel drive,0.0,14.216032
4,240,1.0,156.0,2436.633616,17.0,2015,Europe,Diesel,Front-wheel drive,1.0,18.016395
...,...,...,...,...,...,...,...,...,...,...,...
1936,200,1.0,171.0,3153.197854,16.1,2006,USA,Diesel,Front-wheel drive,1.0,14.310263
1937,220,3.0,189.0,4049.205206,16.5,2012,Asia,Gasoline,All-wheel drive,0.0,10.164457
1938,210,3.0,171.0,3500.001350,13.4,2022,Asia,Gasoline,All-wheel drive,0.0,13.354373
1939,240,2.0,238.0,2883.491696,13.7,2021,Asia,Diesel,All-wheel drive,0.0,17.038592
1940,170,3.0,189.0,2944.314666,19.0,2021,Europe,Gasoline,Front-wheel drive,2.0,15.026741

In [14]:
## target variable
y_train = df_train.fuel_efficiency_mpg
y_val = df_val.fuel_efficiency_mpg
y_test = df_test.fuel_efficiency_mpg

In [15]:
y_test

0       15.865949
1       17.885965
2       10.882701
3       14.216032
4       18.016395
          ...
1936    14.310263
1937    10.164457
1938    13.354373
1939    17.038592
1940    15.026741
Name: fuel_efficiency_mpg, Length: 1941, dtype: float64

In [17]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']