In [60]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [61]:
#!wget https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv

In [62]:
df = pd.read_csv('car_fuel_efficiency.csv')
df.head()

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,3.0,159.0,3413.433759,17.7,2003,Europe,Gasoline,All-wheel drive,0.0,13.231729
1,130,5.0,97.0,3149.664934,17.8,2007,USA,Gasoline,Front-wheel drive,0.0,13.688217
2,170,NaN,78.0,3079.038997,15.1,2018,Europe,Gasoline,Front-wheel drive,0.0,14.246341
3,220,4.0,NaN,2542.392402,20.2,2009,USA,Diesel,All-wheel drive,2.0,16.912736
4,210,1.0,140.0,3460.870990,14.4,2009,Europe,Gasoline,All-wheel drive,2.0,12.488369

In [63]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9704 entries, 0 to 9703
Data columns (total 11 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   engine_displacement  9704 non-null   int64
 1   num_cylinders        9222 non-null   float64
 2   horsepower           8996 non-null   float64
 3   vehicle_weight       9704 non-null   float64
 4   acceleration         8774 non-null   float64
 5   model_year           9704 non-null   int64
 6   origin               9704 non-null   object
 7   fuel_type            9704 non-null   object
 8   drivetrain           9704 non-null   object
 9   num_doors            9202 non-null   float64
 10  fuel_efficiency_mpg  9704 non-null   float64
dtypes: float64(6), int64(2), object(3)
memory usage: 834.1+ KB

In [64]:
## fill missing values
df = df.fillna(0)

In [65]:
df.isnull().sum()

engine_displacement    0
num_cylinders          0
horsepower             0
vehicle_weight         0
acceleration           0
model_year             0
origin                 0
fuel_type              0
drivetrain             0
num_doors              0
fuel_efficiency_mpg    0
dtype: int64

In [66]:
from sklearn.model_selection import train_test_split

In [67]:
df_full_train , df_test = train_test_split(df, test_size = 0.2, random_state = 1)
df_train, df_val = train_test_split(df_full_train, test_size=0.25, random_state =1)

In [68]:
df_train = df_train.reset_index(drop =True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

In [69]:
df_test

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors,fuel_efficiency_mpg
0,170,4.0,170.0,2770.744260,16.9,2004,Europe,Diesel,Front-wheel drive,0.0,15.865949
1,230,5.0,135.0,2546.670530,11.5,2001,Europe,Gasoline,Front-wheel drive,1.0,17.885965
2,160,4.0,179.0,3845.204498,14.9,2021,Asia,Diesel,All-wheel drive,1.0,10.882701
3,230,5.0,0.0,3006.216277,14.7,2017,Europe,Diesel,All-wheel drive,0.0,14.216032
4,240,1.0,156.0,2436.633616,17.0,2015,Europe,Diesel,Front-wheel drive,1.0,18.016395
...,...,...,...,...,...,...,...,...,...,...,...
1936,200,1.0,171.0,3153.197854,16.1,2006,USA,Diesel,Front-wheel drive,1.0,14.310263
1937,220,3.0,189.0,4049.205206,16.5,2012,Asia,Gasoline,All-wheel drive,0.0,10.164457
1938,210,3.0,171.0,3500.001350,13.4,2022,Asia,Gasoline,All-wheel drive,0.0,13.354373
1939,240,2.0,238.0,2883.491696,13.7,2021,Asia,Diesel,All-wheel drive,0.0,17.038592
1940,170,3.0,189.0,2944.314666,19.0,2021,Europe,Gasoline,Front-wheel drive,2.0,15.026741

In [70]:
## target variable
y_train = df_train.fuel_efficiency_mpg
y_val = df_val.fuel_efficiency_mpg
y_test = df_test.fuel_efficiency_mpg

In [71]:
y_test

0       15.865949
1       17.885965
2       10.882701
3       14.216032
4       18.016395
          ...
1936    14.310263
1937    10.164457
1938    13.354373
1939    17.038592
1940    15.026741
Name: fuel_efficiency_mpg, Length: 1941, dtype: float64

In [72]:
del df_train['fuel_efficiency_mpg']
del df_val['fuel_efficiency_mpg']
del df_test['fuel_efficiency_mpg']

In [73]:
df_train

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors
0,120,5.0,169.0,2966.679505,13.9,2005,USA,Gasoline,Front-wheel drive,-1.0
1,200,3.0,143.0,2950.822121,17.1,2013,Asia,Diesel,Front-wheel drive,-1.0
2,180,6.0,180.0,3078.221669,17.4,2007,USA,Gasoline,All-wheel drive,0.0
3,280,5.0,174.0,2797.991793,0.0,2016,USA,Diesel,All-wheel drive,0.0
4,250,4.0,133.0,2362.426930,16.3,2010,USA,Diesel,Front-wheel drive,-1.0
...,...,...,...,...,...,...,...,...,...,...
5817,230,3.0,176.0,3430.993044,17.9,2022,Europe,Diesel,All-wheel drive,0.0
5818,250,4.0,180.0,3067.664350,15.7,2010,Asia,Diesel,All-wheel drive,-1.0
5819,230,2.0,182.0,3041.964593,16.7,2010,Europe,Diesel,All-wheel drive,0.0
5820,180,7.0,147.0,2453.341430,15.2,2015,Europe,Gasoline,All-wheel drive,0.0
5821,190,2.0,138.0,2833.899434,14.1,2017,USA,Diesel,Front-wheel drive,0.0

In [74]:
df_test

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors
0,170,4.0,170.0,2770.744260,16.9,2004,Europe,Diesel,Front-wheel drive,0.0
1,230,5.0,135.0,2546.670530,11.5,2001,Europe,Gasoline,Front-wheel drive,1.0
2,160,4.0,179.0,3845.204498,14.9,2021,Asia,Diesel,All-wheel drive,1.0
3,230,5.0,0.0,3006.216277,14.7,2017,Europe,Diesel,All-wheel drive,0.0
4,240,1.0,156.0,2436.633616,17.0,2015,Europe,Diesel,Front-wheel drive,1.0
...,...,...,...,...,...,...,...,...,...,...
1936,200,1.0,171.0,3153.197854,16.1,2006,USA,Diesel,Front-wheel drive,1.0
1937,220,3.0,189.0,4049.205206,16.5,2012,Asia,Gasoline,All-wheel drive,0.0
1938,210,3.0,171.0,3500.001350,13.4,2022,Asia,Gasoline,All-wheel drive,0.0
1939,240,2.0,238.0,2883.491696,13.7,2021,Asia,Diesel,All-wheel drive,0.0
1940,170,3.0,189.0,2944.314666,19.0,2021,Europe,Gasoline,Front-wheel drive,2.0

In [75]:
df_val

,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,model_year,origin,fuel_type,drivetrain,num_doors
0,210,6.0,151.0,2255.750322,20.9,2013,Europe,Gasoline,Front-wheel drive,-1.0
1,200,6.0,145.0,2921.328272,15.4,2008,USA,Diesel,Front-wheel drive,0.0
2,190,4.0,133.0,2357.787514,13.8,2018,Asia,Diesel,All-wheel drive,2.0
3,250,3.0,105.0,2988.730170,16.0,2012,Asia,Diesel,All-wheel drive,0.0
4,220,3.0,93.0,3174.840838,20.2,2015,Asia,Gasoline,All-wheel drive,0.0
...,...,...,...,...,...,...,...,...,...,...
1936,220,0.0,191.0,2698.807065,17.0,2006,USA,Diesel,Front-wheel drive,0.0
1937,100,2.0,0.0,3545.272512,15.5,2022,Asia,Gasoline,Front-wheel drive,1.0
1938,220,3.0,182.0,3068.941284,21.1,2012,USA,Gasoline,Front-wheel drive,0.0
1939,250,2.0,156.0,3256.003858,17.5,2003,Asia,Gasoline,All-wheel drive,1.0
1940,200,3.0,184.0,2923.067480,0.0,2012,Asia,Diesel,All-wheel drive,1.0

In [76]:
# Decision Tree Regressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.feature_extraction import DictVectorizer

In [77]:
train_dicts = df_train.to_dict(orient = 'records')

In [78]:
dv = DictVectorizer(sparse = False)
X_train = dv.fit_transform(train_dicts)

In [79]:
dtr = DecisionTreeRegressor(max_depth=1)
dtr.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=1)

In [80]:
val_dicts = df_val.to_dict(orient = 'records')
X_val = dv.transform(val_dicts)

In [81]:
y_pred = dtr.predict(X_val)

In [89]:
from sklearn.metrics import mean_squared_error,mean_absolute_error, r2_score

mae = mean_absolute_error(y_val, y_pred)
rmse = np.sqrt(mean_squared_error(y_val, y_pred))
r2 = r2_score(y_val, y_pred)

In [92]:
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"R²: {r2:.2f}")

MAE: 1.28
RMSE: 1.61
R²: 0.61